name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: v22
    - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8
      with:
        toolchain: stable
        cache-workspaces: "src-tauri -> target"
    - uses: tauri-apps/tauri-action@fd1ea0d8e31d0f8670cf14c79c076d85caf9fb53
      with:
        tagName: ${{ github.ref_name }}
        releaseName: "ExamCountdown v__VERSION__"
        releaseBody: "See the assets to download and install this version."
        releaseDraft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
