name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable
      
    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: v22

    - name: Install frontend dependencies
      run: npm install
      # 使用tauri actions
      
    - name: Build the app
      id: build
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
      with:
        tagName: ${{ github.ref_name }}
        releaseName: "ComfyUI Startup v__VERSION__"
        releaseBody: "See the assets to download and install this version."
        releaseDraft: true
        prerelease: false
  
    - name: Upload assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 运行自己的脚本
      run: node updater.mjs