name: Electron Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: v22
      
    - name: Publish
      run: npm run publish
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
